### ISSUE TITLE
What a great project!

### ISSUE THREAD

**Issue by cappannonno** [xang555/facerecon_dashboard#1]
Hi! Your project is great! I was looking for something like this but am I the lone which cannot start the web dashboard. Is it a known issue? :)

**Comment by xang555** [comment]
> Hi! Your project is great! I was looking for something like this but am I the lone which cannot start the web dashboard. Is it a known issue? :)

what is your error message? can you post error message when you start dashboard ?

**Comment by cappannonno** [comment]
Yes, sorry.
I can run succesfully "npm install" but when I run "npm start" I get this error:
`Failed to compile.

./src/views/unknown_user/UnknownUser.jsx
Module not found: Can't resolve 'antd/node_modules/moment' in 'C:\facerecon_dashboard-master\src\views\unknown_user'
Error from chokidar (C:\node_modules): Error: EBUSY: resource busy or locked, lstat 'C:\DumpStack.log.tmp'
Error from chokidar (C:\node_modules): Error: EBUSY: resource busy or locked, lstat 'C:\hiberfil.sys'
Error from chokidar (C:\node_modules): Error: EBUSY: resource busy or locked, lstat 'C:\pagefile.sys'
Error from chokidar (C:\node_modules): Error: EBUSY: resource busy or locked, lstat 'C:\swapfile.sys'
Error from chokidar (C:\node_modules): Error: EBUSY: resource busy or locked, lstat 'C:\DumpStack.log.tmp'
Error from chokidar (C:\node_modules): Error: EBUSY: resource busy or locked, lstat 'C:\hiberfil.sys'
Error from chokidar (C:\node_modules): Error: EBUSY: resource busy or locked, lstat 'C:\pagefile.sys'
Error from chokidar (C:\node_modules): Error: EBUSY: resource busy or locked, lstat 'C:\swapfile.sys'`

And in localhost:3000 I get the following screen:
![image](https://user-images.githubusercontent.com/16478304/85881402-d3f62200-b7dd-11ea-9c64-a20656d13fca.png)

**Comment by xang555** [comment]
> Yes, sorry.
> I can run succesfully "npm install" but when I run "npm start" I get this error:
> `Failed to compile.
> 
> ./src/views/unknown_user/UnknownUser.jsx
> Module not found: Can't resolve 'antd/node_modules/moment' in 'C:\facerecon_dashboard-master\src\views\unknown_user'
> Error from chokidar (C:\node_modules): Error: EBUSY: resource busy or locked, lstat 'C:\DumpStack.log.tmp'
> Error from chokidar (C:\node_modules): Error: EBUSY: resource busy or locked, lstat 'C:\hiberfil.sys'
> Error from chokidar (C:\node_modules): Error: EBUSY: resource busy or locked, lstat 'C:\pagefile.sys'
> Error from chokidar (C:\node_modules): Error: EBUSY: resource busy or locked, lstat 'C:\swapfile.sys'
> Error from chokidar (C:\node_modules): Error: EBUSY: resource busy or locked, lstat 'C:\DumpStack.log.tmp'
> Error from chokidar (C:\node_modules): Error: EBUSY: resource busy or locked, lstat 'C:\hiberfil.sys'
> Error from chokidar (C:\node_modules): Error: EBUSY: resource busy or locked, lstat 'C:\pagefile.sys'
> Error from chokidar (C:\node_modules): Error: EBUSY: resource busy or locked, lstat 'C:\swapfile.sys'`
> 
> And in localhost:3000 I get the following screen:
> ![image](https://user-images.githubusercontent.com/16478304/85881402-d3f62200-b7dd-11ea-9c64-a20656d13fca.png)

please, update repo or clone repo again and try re-install (`npm install`) this is bug when install dependencies in `windows` i'm fixed it! thanks for your report

**Comment by cappannonno** [comment]
That's great! It's working 👍
